export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const RECEIVE_PLAYER_DETAILS = 'RECEIVE_PLAYER_DETAILS';
export const RESET_PLAYER_DETAILS = 'RESET_PLAYER_DETAILS';
export const CLEAR_PLAYER_DETAILS = 'CLEAR_PLAYER_DETAILS';
export const RECEIVE_PLAYER_LIST = 'RECEIVE_PLAYER_LIST';
export const RESET_PLAYER = 'RESET_PLAYER';

export const RECEIVE_TOP_PLAYERS = 'RECEIVE_TOP_PLAYERS';
export const RECEIVE_WEEKS = 'RECEIVE_WEEKS';